name: Upload Python Package

on:
  push:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose your desired Python version (e.g., 3.9)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install pygame

      - name: Build package
        run: python -m build

      - name: Publish package
        run: |
          python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__  # Your PyPI username (usually "__token__")
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
